### ISSUE TITLE
BetterFolders - Pressing custom icon causes crash 

### ISSUE THREAD

**Issue by Jamie-Fairweather** [Zerthox/BetterDiscord-Plugins#122]
Pressing the custom icon button crashes discord with this error:

`[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
TypeError: FolderIcon is not a function
at BetterFolderIcon (betterdiscord://plugins/BetterFolders.plugin.js:370:20)
Component stack:
at BetterFolderIcon (betterdiscord://plugins/BetterFolders.plugin.js:369:29)
at div
at I (https://discord.com/assets/b7b15ebc97eabb225225.js:3552:537)
at BetterFolderUploader (betterdiscord://plugins/BetterFolders.plugin.js:376:33)
at l (https://discord.com/assets/b7b15ebc97eabb225225.js:3630:408)
at div
at p (https://discord.com/assets/95bdc3467a6f9704427a.js:17:159)
at form
at h (https://discord.com/assets/b7b15ebc97eabb225225.js:2246:546)
at div
at https://discord.com/assets/b7b15ebc97eabb225225.js:3813:564
at w (https://discord.com/assets/b7b15ebc97eabb225225.js:3726:795)
at h (https://discord.com/assets/b7b15ebc97eabb225225.js:2246:546)
at div
at https://discord.com/assets/b7b15ebc97eabb225225.js:248:313
at h (https://discord.com/assets/b7b15ebc97eabb225225.js:2246:546)
at div
at https://discord.com/assets/b7b15ebc97eabb225225.js:3547:452
at M (https://discord.com/assets/b7b15ebc97eabb225225.js:3725:13)
at t (https://discord.com/assets/b6739de9b9dd66f45d91.js:3:87)
at div
at S (https://discord.com/assets/b7b15ebc97eabb225225.js:3699:297)
at AppLayer
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:3731:85)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:4697:162)
at N (https://discord.com/assets/b7b15ebc97eabb225225.js:3732:452)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:3698:500)
at VerificationLayerProvider
at E (https://discord.com/assets/b7b15ebc97eabb225225.js:2571:293)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:3698:500)
at AppLayerProvider
at div
at div
at E (https://discord.com/assets/b7b15ebc97eabb225225.js:1987:176)
at h (https://discord.com/assets/b7b15ebc97eabb225225.js:2246:546)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:704:655)
at T (https://discord.com/assets/b7b15ebc97eabb225225.js:708:113)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:708:584)
at u (https://discord.com/assets/b7b15ebc97eabb225225.js:4341:151)
at m (https://discord.com/assets/b7b15ebc97eabb225225.js:688:819)
at re (https://discord.com/assets/b7b15ebc97eabb225225.js:692:313)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:750:101)
at u (https://discord.com/assets/b7b15ebc97eabb225225.js:4340:85)
at https://discord.com/assets/b7b15ebc97eabb225225.js:4861:30
at H (https://discord.com/assets/b7b15ebc97eabb225225.js:6008:700)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:6191:570)
at t (https://discord.com/assets/b7b15ebc97eabb225225.js:6147:817)
at f (https://discord.com/assets/b7b15ebc97eabb225225.js:2617:956)`

**Comment by Zerthox** [comment]
Hmm doesnt seem related to a Discord update, I am unable to reproduce. Which version of the plugin are you running? And which version of Discord?

**Comment by Jamie-Fairweather** [comment]
Okay, so I've done a little bit of testing. The issue comes from incapability with another plugin; DisplayServersAsChannels, I was kinda hoping your plugin would allow me to change the default folder icon that DisplayServersAsChannels uses.

Both plugins are latest.
Discord is Stable 144057
BD is 1.6.3

**Comment by Zerthox** [comment]
Ah that explains it. The plugin is unable to find the folder icon component since the other plugin has replaced the structure of the guilds list with its own. You should ask for DisplayServersAsChannels to include an option to change the icon.
