### ISSUE TITLE
Error when compiling VoiceEvents

### ISSUE THREAD

**Issue by xXTacticalWaffleXx** [Zerthox/BetterDiscord-Plugins#134]
### Bug description

When i start discord with this plugin installed discord says that there was an error compling the plugin and throws the following error

> Error: Accessing meta before initialization
    at getMeta (betterdiscord://plugins/VoiceEvents.plugin.js:63:15)
    at print (betterdiscord://plugins/VoiceEvents.plugin.js:159:49)
    at error (betterdiscord://plugins/VoiceEvents.plugin.js:162:28)
    at findDefaultVoice (betterdiscord://plugins/VoiceEvents.plugin.js:389:9)
    at eval (betterdiscord://plugins/VoiceEvents.plugin.js:414:12)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

i am on linux if that important and im using the version of discord for the community arch repo

### Plugin

voiceevents

### Plugin version

v2.4.0

### Discord client

Stable

**Comment by Zerthox** [comment]
This is an error occuring while trying to report an error. Discord on Linux can have no speech synthesis voice available, which makes the plugin unable to work properly. For more info see #55 and #27. I will fix the alert modal that is supposed to be shown.
