### ISSUE TITLE
emulator: settings button throws an error

### ISSUE THREAD

**Issue by AceLikesGhosts** [Zerthox/BetterDiscord-Plugins#158]
### Bug description

Reproduction steps:
1. Build the Emulator and put into plugin's folder
2. Navigate to Plugins page and press the `settings` gear button

Error:
```
TypeError: Cannot read properties of undefined (reading 'WINDOWS')
    at SettingsPanel (Emulator.plugin.js:366:40)
    at Sa (e1d0a488e89ed40017dd.js:1784:54)
    at gu (e1d0a488e89ed40017dd.js:1838:146)
    at Ic (e1d0a488e89ed40017dd.js:1831:89)
    at mc (e1d0a488e89ed40017dd.js:1831:17)
    at hc (e1d0a488e89ed40017dd.js:1830:867)
    at oc (e1d0a488e89ed40017dd.js:1827:642)
    at uc (e1d0a488e89ed40017dd.js:1828:49)
    at Fi (e1d0a488e89ed40017dd.js:1767:577)
    at e1d0a488e89ed40017dd.js:1825:555
```

### Plugin

Emulator

### Plugin version

2.0.0

### Discord client

Stable

**Comment by Zerthox** [comment]
The plugin has been completely broken for nearly a year due to Discord changing internal modules. I'm open to any PRs updating it.
