### ISSUE TITLE
CollapseEmbeds - crashes when opening channels with images

### ISSUE THREAD

**Issue by Razzaline** [Zerthox/BetterDiscord-Plugins#162]
### Bug description

If images are visible upon opening a channel, Discord will crash before the channel can properly load.

ReactJS error from console:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

Here's the component stack if that helps at all:
```
Component stack:
     at div
    at M (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11485:462)
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2738:243)
    at div
    at O (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:9109:567)
    at Hider (betterdiscord://plugins/CollapseEmbeds.plugin.js:373:18)
    at t (https://canary.discord.com/assets/72bad8e24e69be0c8311.js:11:258)
    at div
    at n (https://canary.discord.com/assets/08d1975837b966b125eb.js:367:62)
    at Nc (https://canary.discord.com/assets/08d1975837b966b125eb.js:379:228)
    at div
    at M (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11485:462)
    at betterdiscord/renderer.js:4:30222
    at li
    at M (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11485:462)
    at Lr (https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:1318:189)
    at ol
    at div
    at L (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11484:853)
    at div
    at https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3161:547
    at div
    at v (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:10196:479)
    at Cc (https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:1429:11)
    at https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:1434:568
    at u (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2754:694)
    at main
    at In (https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:206:883)
    at https://canary.discord.com/assets/42b7b5f17a3259e23c0d.js:578:135
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2836:705)
    at ChatLayerProvider
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2663:778)
    at n (https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:214:755)
    at https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:220:893
    at div
    at div
    at o (https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:161:44)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1618:594)
    at https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2707:253
    at https://canary.discord.com/assets/1f5494db9fc1fa5f9446.js:174:858
    at oue (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1358:194)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1927:221)
    at betterdiscord/renderer.js:4:30222
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1928:166)
    at div
    at div
    at div
    at gue (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1361:870)
    at div
    at l (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:265:197)
    at n (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1398:652)
    at div
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11044:625)
    at n (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1401:221)
    at sde (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1402:296)
    at div
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3186:767)
    at ude (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1402:616)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1927:221)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1928:166)
    at i (https://canary.discord.com/assets/fe1ad4d52c46602ad345.js:1450:929)
    at Suspense
    at f
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1927:221)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1928:166)
    at div
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2836:705)
    at VerificationLayerProvider
    at p (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:5808:115)
    at Te (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2551:443)
    at div
    at div
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2836:705)
    at AppLayerProvider
    at E (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:5082:512)
    at L (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:11484:853)
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2585:379)
    at O (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2588:961)
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2589:655)
    at a (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:10475:533)
    at _ (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2757:880)
    at p (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2539:902)
    at p (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2982:209)
    at l (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:7831:671)
    at en (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2570:508)
    at n (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3272:245)
    at https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3276:827
    at a (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:10474:563)
    at https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1729:942
    at Dt (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1738:248)
    at un (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3043:504)
    at App
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1924:520)
    at t (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:1881:436)
    at ir (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:3304:935)
    at p (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:2982:209)
    at l (https://canary.discord.com/assets/355762d2725bf4c7f8f7.js:7831:671)
    ```

### Plugin

CollapseEmbeds

### Plugin version

1.0.1

### Discord client

Canary

**Comment by Zerthox** [comment]
This issue seems to be only present on Canary as of right now. Since Canary changes sometimes never make it to stable, this is low priority for now.

**Comment by M0REKZ** [comment]
it actually is crashing discord stable on my side..

**Comment by Primus1243** [comment]
Crashing on stable here too.
Version 1.0.2 for Collapse Embeds
Discord version is Stable 230958 (9378b16)
Better discord version is version 1.9.3

Crashes anytime I open any channels that have images or videos.

**Comment by Araxnus** [comment]
Crashing on stable here as well, I turned all my other plugins off one by one and found out that it was CollapseEmbeds that was the issue.

**Comment by ImAFrogOwO** [comment]
No this isnt just a Canary issue. what fixed it for me was
```js
const Arrow = bySource(["d:\"M16."]);//, (source) => /\.open[,;]/.test(source)]);
```
