### ISSUE TITLE
CollapseEmbeds - broken settings menu

### ISSUE THREAD

**Issue by Razzaline** [Zerthox/BetterDiscord-Plugins#163]
### Bug description

When opening the settings inside the BetterDiscord plugins menu, it displays "There was an unexpected Error. Click to open console for more details."

The console output:
```
3fecf3886e59584c5ad6.js:538 TypeError: Cannot read properties of undefined (reading 'marginTop20')
    at SettingsContainer (CollapseEmbeds.plugin.js:252:74)
    at Sa (355762d2725bf4c7f8f7.js:1807:54)
    at gu (355762d2725bf4c7f8f7.js:1861:146)
    at Ic (355762d2725bf4c7f8f7.js:1854:89)
    at mc (355762d2725bf4c7f8f7.js:1854:17)
    at hc (355762d2725bf4c7f8f7.js:1853:867)
    at oc (355762d2725bf4c7f8f7.js:1850:642)
    at uc (355762d2725bf4c7f8f7.js:1851:49)
    at Fi (355762d2725bf4c7f8f7.js:1790:577)
    at 355762d2725bf4c7f8f7.js:1848:555
```

Seems to be the same as #161 and #160.

### Plugin

CollapseEmbeds

### Plugin version

1.0.1

### Discord client

Canary

**Comment by Zerthox** [comment]
Same issue as #160.
