### ISSUE TITLE
OnlineFriendCount crashes Discord

### ISSUE THREAD

**Issue by Razzaline** [Zerthox/BetterDiscord-Plugins#167]
### Bug description

Enabling the plugin immediately crashes Discord. 

CrashRecovery log:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 
Component stack:
     at div
    at Item (betterdiscord://plugins/OnlineFriendCount.plugin.js:475:17)
    at CounterItem (betterdiscord://plugins/OnlineFriendCount.plugin.js:476:24)
    at div
    at CountersContainer (betterdiscord://plugins/OnlineFriendCount.plugin.js:493:48)
    at M (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:196258)
    at div
    at https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:23592
    at ul
    at nav
    at c (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:403110)
    at https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:403535
    at FCHook (betterdiscord://plugins/BetterFolders.plugin.js:244:29)
    at S (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:1118573)
    at betterdiscord/renderer.js:5:28216
    at div
    at eU (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:27610)
    at div
    at s (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:105360)
    at D (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:271320)
    at div
    at o (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:1356235)
    at P (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:271574)
    at y (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:272551)
    at div
    at u (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:195292)
    at https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:255907
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167115)
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167803)
    at ti (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:91355)
    at Suspense
    at d
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167115)
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167803)
    at div
    at _ (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:102769)
    at VerificationLayerProvider
    at c (https://canary.discord.com/assets/749d021efa0a4307e599.js:1:45142)
    at I (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1427942)
    at div
    at div
    at _ (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:102769)
    at AppLayerProvider
    at A (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1368725)
    at M (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:196258)
    at M (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:32613)
    at S (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1436746)
    at N (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1437201)
    at s (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1629075)
    at l (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:88648)
    at E (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:14467)
    at d (https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:49339)
    at d (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:74396)
    at er (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1433269)
    at X (https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:6119)
    at https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:11200
    at s (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1628266)
    at https://canary.discord.com/assets/fcfa42394503368b920f.js:1:218000
    at u (https://canary.discord.com/assets/fcfa42394503368b920f.js:1:212167)
    at E (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:69203)
    at App
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:164397)
    at t (https://canary.discord.com/assets/7f212d7b2214b392def0.js:1:863243)
    at o (https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:35606)
    at d (https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:49339)
    at d (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:74396)
```
    
Other console logs:
```
    OnlineFriendCount.plugin.js:284 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'return')
    at queryFiber (OnlineFriendCount.plugin.js:284:28)
    at findOwner (OnlineFriendCount.plugin.js:306:12)
    at eval (OnlineFriendCount.plugin.js:309:19)
    at new Promise (<anonymous>)
    at forceFullRerender (OnlineFriendCount.plugin.js:308:38)
    at triggerRerender (OnlineFriendCount.plugin.js:515:15)
    at stop (OnlineFriendCount.plugin.js:544:9)
    at Object.stop (OnlineFriendCount.plugin.js:416:19)
    at D.stopPlugin (renderer.js:5:34835)
    at D.stopAddon (renderer.js:5:34143)
```

### Plugin

OnlineFriendCount

### Plugin version

3.1.2

### Discord client

Canary

**Comment by Razzaline** [comment]
Sorry, I didn't realise it didn't automatically update. Here's the console log after updating to 3.1.3:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 
Component stack:
     at div
    at Item (betterdiscord://plugins/OnlineFriendCount.plugin.js:475:17)
    at CounterItem (betterdiscord://plugins/OnlineFriendCount.plugin.js:476:24)
    at div
    at CountersContainer (betterdiscord://plugins/OnlineFriendCount.plugin.js:493:48)
    at M (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:196258)
    at div
    at https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:23592
    at ul
    at nav
    at c (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:403110)
    at https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:403535
    at FCHook (betterdiscord://plugins/BetterFolders.plugin.js:244:29)
    at S (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:1118573)
    at betterdiscord/renderer.js:5:28216
    at div
    at eU (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:27610)
    at div
    at s (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:105360)
    at D (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:271320)
    at div
    at o (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:1356235)
    at P (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:271574)
    at y (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:272551)
    at div
    at u (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:195292)
    at https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:255907
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167115)
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167803)
    at ti (https://canary.discord.com/assets/bafdf40284c1dfa7e213.js:1:91355)
    at Suspense
    at d
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167115)
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:167803)
    at div
    at _ (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:102769)
    at VerificationLayerProvider
    at c (https://canary.discord.com/assets/749d021efa0a4307e599.js:1:45142)
    at I (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1427942)
    at div
    at div
    at _ (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:102769)
    at AppLayerProvider
    at A (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1368725)
    at M (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:196258)
    at M (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:32613)
    at S (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1436746)
    at N (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1437201)
    at s (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1629075)
    at l (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:88648)
    at E (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:14467)
    at d (https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:49339)
    at d (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:74396)
    at er (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1433269)
    at X (https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:6119)
    at https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:11200
    at s (https://canary.discord.com/assets/7fc1d3de231afbfb9879.js:1:1628266)
    at https://canary.discord.com/assets/fcfa42394503368b920f.js:1:218000
    at u (https://canary.discord.com/assets/fcfa42394503368b920f.js:1:212167)
    at E (https://canary.discord.com/assets/844d702d3367ffbc5d6a.js:1:69203)
    at App
    at e (https://canary.discord.com/assets/0cbd3f62b315bf33697e.js:1:164397)
    at t (https://canary.discord.com/assets/7f212d7b2214b392def0.js:1:863243)
    at o (https://canary.discord.com/assets/755990448ebd249ad8dd.js:1:35606)
    at d (https://canary.discord.com/assets/60591f8265b6d8e02789.js:1:49339)
    at d (https://canary.discord.com/assets/f69c4746b030420d8500.js:1:74396)
```

The other one wasn't there this time.

**Comment by Zerthox** [comment]
The update hasn't been approved for the BetterDiscord site yet, that's why you didn't get an update notification.

**Comment by Zomaholic** [comment]
3.1.3 is also crashing betterdiscord

**Comment by ImAFrogOwO** [comment]
Nahhh I am pretty sure theres something wrong with your fix.
```js
const Item = ({ children, className, link }) => (React.createElement("div", { className: listStyles.listItem }, link ? (React.createElement(Link, { to: link, className: classNames(styles.item, styles.link, className) }, children)) : (React.createElement("div", { className: classNames(styles.link, className) }, children))));
```
apparently is crashing react with is crashing discord. Not sure if its just me
