### ISSUE TITLE
BetterVolume no longer works

### ISSUE THREAD

**Issue by nate101pro** [Zerthox/BetterDiscord-Plugins#190]
### Bug description

When enabled shows this error:

SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.ensurePluginData (betterdiscord/renderer.js:5:14572)
    at Object.getPluginData (betterdiscord/renderer.js:5:14673)
    at Dt.load (betterdiscord/renderer.js:5:409726)
    at load (betterdiscord://plugins/BetterVolume.plugin.js:70:34)
    at SettingsStore.load (betterdiscord://plugins/BetterVolume.plugin.js:256:47)
    at Object.eval [as exports] (betterdiscord://plugins/BetterVolume.plugin.js:319:15)
    at N.initializeAddon (betterdiscord/renderer.js:5:27025)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

### Plugin

BetterVolume

### Plugin version

3.0.0

### Discord client

Stable

**Comment by Zerthox** [comment]
The plugin's settings file is invalid. Did you touch it yourself in any way? If not, this might be a bug in BetterDiscord.

**Comment by nate101pro** [comment]
> The plugin's settings file is invalid. Did you touch it yourself in any way? If not, this might be a bug in BetterDiscord.

No, i just found this plugin a month ago and suddenly it started failing i've reinstalled this plugin multiple times.

**Comment by nate101pro** [comment]
Thank you for that little bit of information though seems like removing BetterVolume.config.json and restarting BD gets the plugin working, I forgot removing plugins via BD does not remove the config.json files.  I never messed with the files though nor the settings of the plugin so idk how it got messed up.
