### ISSUE TITLE
dont started

### ISSUE THREAD

**Issue by VeryEvilBatman** [Zerthox/BetterDiscord-Plugins#196]
### Bug description

SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.ensurePluginData (betterdiscord/renderer.js:5:15980)
    at Object.getPluginData (betterdiscord/renderer.js:5:16081)
    at Dt.load (betterdiscord/renderer.js:5:418071)
    at load (betterdiscord://plugins/BetterVolume.plugin.js:70:34)
    at SettingsStore.load (betterdiscord://plugins/BetterVolume.plugin.js:256:47)
    at Object.eval [as exports] (betterdiscord://plugins/BetterVolume.plugin.js:319:15)
    at N.initializeAddon (betterdiscord/renderer.js:5:28441)
    at N.loadAddon (betterdiscord/renderer.js:5:7813)
    at N.loadAddon (betterdiscord/renderer.js:5:27685)
    at N.loadAllAddons (betterdiscord/renderer.js:5:10685)
    at N.initialize (betterdiscord/renderer.js:5:4500)
    at N.initialize (betterdiscord/renderer.js:5:26798)
    at Object.startup (betterdiscord/renderer.js:5:416934)

### Plugin

BetterVolume

### Plugin version

v3.1.0

### Discord client

Stable

**Comment by Zerthox** [comment]
See #195

**Comment by VeryEvilBatman** [comment]
> See #195

thx, after delete BetterVolume.config.json  it started working again
