### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by kjasdADadq0w90w** [Zerthox/BetterDiscord-Plugins#72]
The current version of OnlineFriendCount leads to fatal crashing for Discord PTB. BetterDiscord's CrashRecovery cannot diagnose the problem to a specific plugin, but testing each plugin leads to OnlineFriendCount being the culprit.

**Comment by UmBarril** [comment]
For what I have seem here and on the OnlineFriendCount official BD page, the most recent version is 1.5.0 (pls correct me if I'm wrong)
I have tried to reinstall it again but it keeps crashing on loading

That's the error I get when I try to run it:

[2021-10-30 14:08:09.874][CONSOLE:ERROR] {} Cannot read property 'FRIEND' of undefined
TypeError: Cannot read property 'FRIEND' of undefined
    at betterdiscord://plugins/OnlineFriendCount.plugin.js:121:52
    at Array.filter (<anonymous>)
    at betterdiscord://plugins/OnlineFriendCount.plugin.js:120:52
    at u.a [as memoizedGetStateFromStores] (https://discord.com/assets/71e87549ca9fa8b56538.js:3989:137)
    at u.l.render (https://discord.com/assets/71e87549ca9fa8b56538.js:3988:681)
    at qo (https://discord.com/assets/71e87549ca9fa8b56538.js:5593:489)
    at Xo (https://discord.com/assets/71e87549ca9fa8b56538.js:5593:288)
    at $s (https://discord.com/assets/71e87549ca9fa8b56538.js:5633:166)
    at Gu (https://discord.com/assets/71e87549ca9fa8b56538.js:5623:748)
    at wu (https://discord.com/assets/71e87549ca9fa8b56538.js:5623:676)
    at Uu (https://discord.com/assets/71e87549ca9fa8b56538.js:5623:539)
    at yu (https://discord.com/assets/71e87549ca9fa8b56538.js:5620:164)
    at https://discord.com/assets/71e87549ca9fa8b56538.js:5565:340
    at t.unstable_runWithPriority (https://discord.com/assets/71e87549ca9fa8b56538.js:5859:320)
    at Ka (https://discord.com/assets/71e87549ca9fa8b56538.js:5565:117)
    at qa (https://discord.com/assets/71e87549ca9fa8b56538.js:5565:285)
    at Xa (https://discord.com/assets/71e87549ca9fa8b56538.js:5565:220)
    at Tu (https://discord.com/assets/71e87549ca9fa8b56538.js:5617:510)
    at Object.enqueueForceUpdate (https://discord.com/assets/71e87549ca9fa8b56538.js:5569:521)
    at u.h.forceUpdate (https://discord.com/assets/71e87549ca9fa8b56538.js:5835:614)
    at Wrapper.triggerRerender (betterdiscord://plugins/OnlineFriendCount.plugin.js:171:29)
    at Wrapper.start (betterdiscord://plugins/OnlineFriendCount.plugin.js:141:14)
    at Wrapper.start (betterdiscord://plugins/OnlineFriendCount.plugin.js:234:15)
    at Object.startPlugin (<anonymous>:4:309642)
    at Object.startAddon (<anonymous>:4:309437)
    at Object.loadAddon (<anonymous>:4:270626)
    at Object.loadAddon (<anonymous>:4:307610)
    at Object.loadAllAddons (<anonymous>:4:272726)
    at Object.initialize (<anonymous>:4:267216)
    at Object.initialize (<anonymous>:4:306820)
    at Object.startup (<anonymous>:4:368806)

**Comment by Zerthox** [comment]
v1.5.1 was released 2 days ago. The update hasnt been approved for the BD website yet (BD staff slacking). You can manually update from the repo or wait.
